# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:

      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # build
      - run:
          name: install
          command: |
            . venv/bin/activate
            bash build.sh --build --make-pkg

      - store_artifacts:
          path: test-reports
          destination: test-reports
