import skmvs as SK

ZILEAN_PATH = SK.get_value("ZILEAN_PATH")
ZILEAN_SCRIPTS = SK.get_value("ZILEAN_SCRIPTS")
ZILEAN_VERSION = SK.get_value("ZILEAN_VERSION")
ZILEAN_API = SK.get_value("ZILEAN_API")
ZILEAN_OFFICE = SK.get_value("ZILEAN_OFFICE")
ZILEAN_CONFIG = SK.get_value("ZILEAN_CONFIG")
