import skmvs as SK

ZILEAN_PATH = SK.get_value("ZILEAN_PATH")
ZILEAN_SCRIPTS = SK.get_value("ZILEAN_SCRIPTS")
ZILEAN_VERSION = SK.get_value("ZILEAN_VERSION")
ZILEAN_WORKING_DIR = SK.get_value("ZILEAN_WORKING_DIR")
